config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/auth/:provider/callback', to: 'sessions#create'
  post '/sessions/create', to: 'sessions#create'
  get '/sessions/new', to: 'sessions#new'
  get '/sessions/destroy', to: 'sessions#destroy'
  resources :tweets

  root to: 'sessions#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user

  validates :user_id, :body, presence: true
  validates :body, length: { maximum: 280 }
  before_create :post_to_twitter
  mount_uploader :image, ImageUploader

  def post_to_twitter
    if check_user_twitter
      if image.blank?
        @obj_twit = user.twitter.update(body)
      else
        uri = open("http://localhost:3000#{image}")
        raise 'Error loading image' unless uri
        @obj_twit = user.twitter.update_with_media(body, uri)
      end
      self.twitter_url = @obj_twit.id
    end
  end

  private

  def check_user_twitter
    ob = User.find(self.user_id)
    ob.provider
  end
end

app/models/user.rb
class User < ApplicationRecord
  #validates :email, uniqueness: true
  #validates :email, :password, presence: true
  def self.find_or_create_from_auth_hash(auth_hash)
    user = where(provider: auth_hash.provider, uid: auth_hash.uid)
    user = user.first_or_create
    p auth_hash
    user.update(
      name: auth_hash.info.nickname,
      profile_image: auth_hash.info.image,
      token: auth_hash.credentials.token,
      secret: auth_hash.credentials.secret
    )
    user
  end

  def twitter
    @client ||= Twitter::REST::Client.new do |config|
      config.consumer_key        = Rails.application.secrets.twitter_api_key
      config.consumer_secret     = Rails.application.secrets.twitter_api_secret
      config.access_token        = token
      config.access_token_secret = secret
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  add_flash_types :success, :danger, :info

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user

  protected

  def require_login
    redirect_to root_path if current_user.blank?
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    if auth_hash.blank?
      if request['commit'] == 'Register'
        registration
      else
        authorization
      end
    else
      @user = User.find_or_create_from_auth_hash(auth_hash)
    end
    if @user.blank?
      flash[:danger] = 'Invalid login or password'
    else
      session[:user_id] = @user.id
    end
    redirect_to root_path
  end

  def destroy
    if current_user
      session.delete(:user_id)
      flash[:success] = 'Sucessfully logged out!'
    end
    redirect_to root_path
  end

  def new
    @user = User.new
  end

  def index
    @user = User.new
  end

  protected

  def auth_hash
    request.env['omniauth.auth']
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :id)
  end

  def authorization
    @user = User.where(email: user_params[:email].to_s)
    @user = @user.where(password: user_params[:password].to_s).first
  end

  def registration
    @user = User.new(user_params)
    @user.name = user_params[:email]
    @user.save
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:show, :destroy]
  before_action :require_login

  def index
    @tweet = Tweet.new
    @tweets = Tweet.where(user_id: session[:user_id].to_s)
    @tweets = @tweets.order('created_at DESC')
  end

  def show
  end

  def new
    @tweet = Tweet.new
  end

  def create
    @tweet = Tweet.new(tweet_params)
    @tweet.user_id = current_user.id
    begin
      if @tweet.save
        redirect_to @tweet, success: 'Tweet successfully created'
      else
        redirect_to @tweet, danger: 'An error occurred creating the tweet'
      end
    rescue
      redirect_to @tweet, danger: 'Error loading image'
    end
  end

  def destroy
    @tweet.destroy
    redirect_to @tweet, success: 'Tweet successfully deleted'
  end

  private

  def set_tweet
    @tweet = Tweet.find(params[:id])
  end

  def tweet_params
    params.require(:tweet).permit(:user_id, :body, :image, :twitter_url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tweeter</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="/">HOME <span class="sr-only">(current)</span></a></li>
        <% if current_user %>
          <li><a href="/tweets">TWEETS</a></li>
        <% end %>
      </ul>
      <% if current_user %>
        <ul class="nav navbar-nav navbar-right">
          <li><a>Signed in as <%= current_user.name %></a> </li>
          <li><a href="/sessions/destroy#" class="txt-red">Exit</a></li>
        </ul>
      <% end %>
    </div>
  </div>
</nav>

<div class="container">
  <div class="row">
    <div class="col-md-12">
      <% flash.each do |name, message| %>
        <div class="alert alert-<%= name %>">
          <%= message %>
        </div>
      <% end %>
    </div>
  </div>
  <div class="row">
    <%= yield %>
  </div>

</body>
</html>

app/views/tweets/index.html.erb
<h1 class="text-center">Tweets</h1>
<div class="container">

  <div class="row">
    <div class="col-md-6 col-md-offset-3 text-center">
      <%= form_for @tweet, url: {action: "create"}, html: {class: "nifty_form"} do |f| %>
        <%= f.text_area :body, size: "30x6", class: "form-control" %></br>
        <%= f.file_field :image %>
        <%= f.submit "Tweet", class: "btn btn-primary btn-lg" %>
      <% end %>
    </div>

  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <p id="notice"><%= notice %></p>
      <% if @tweets.size > 0 %>
        <h1 class="text-center">Listing Tweets</h1>
      <% end %>
      <% @tweets.each do |tweet| %>   
        <div class="col-md-12 form-group tweet_item">
          <div class="col-md-12">
            <%= image_tag(tweet.image.url, alt: 'Image', class: "img-tweets img-responsive") if tweet.image? %>
            <%= tweet.body %>
          </div>
          <div class="col-md-6 text-left"> <%= link_to 'Show', tweet %> |
            <%= link_to 'Destroy', tweet, method: :delete, data: { confirm: 'Are you sure?' } %></div>
          <div class="col-md-6 text-right">
            <%= tweet.created_at.to_s(:ru_datetime) %>
            <% unless current_user.token.blank? %>
            <a id="link_view_tweet" target="blank" href="https://twitter.com/<%= current_user.name %>/status/<%= tweet.twitter_url %>"#>View  </a>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>
<div class="col-md-12 text-center">
  <strong>User:</strong></br>
  <h2 class="txt-blue"><%= current_user.name %></h2>
</div>
<div class="col-md-12 text-center txt-gray">
  <h2><%= @tweet.body %></h2>
</div>
<div class="col-md-4 col-md-offset-4 text-center">
	<%= image_tag(@tweet.image.url, alt: 'Image', class: "img-responsive") if @tweet.image? %>
</div>
<div class="col-md-12 text-center">
  <%= link_to 'Back', tweets_path, class: "btn btn-success" %>
</div>